#cloud-config
hostname: tiny
bootcmd:
  - [ cloud-init-per, always, bootup, python3, /opt/tinybox/setup/bootup.py ]
  - [ cloud-init-per, once, raidsetup, mdadm, --create, /dev/md0, /dev/nvme0n1, /dev/nvme1n1, /dev/nvme2n1, /dev/nvme3n1, --level=0, --raid-devices=4, -f ]
mounts:
  - [ /dev/md0, /raid, auto, "defaults,nofail", "0", "2" ]
user:
  name: tiny
  gecos: tiny
  groups: adm, audio, cdrom, dialout, floppy, lxd, netdev, plugdev, sudo, video, render
  sudo: "ALL=(ALL) NOPASSWD:ALL"
  shell: /bin/bash
  lock_passwd: false
  lock-passwd: false
  plain_text_passwd: tiny
runcmd:
  - [ cloud-init-per, once, firstboot, python3, /opt/tinybox/setup/firstboot.py ]
  - [ cloud-init-per, once, update, apt, update, -y ]
  - [ cloud-init-per, once, upgrade, apt, upgrade, -y ]
  - [ cloud-init-per, always, firstsetup, python3, /opt/tinybox/setup/firstsetup.py ]
